NUM_TRAIN_EPOCHS=40

EVAL_DATASET="CoNLL2003"
qsub -v EVAL_DATASET=${EVAL_DATASET} -v NUM_TRAIN_EPOCHS=${NUM_TRAIN_EPOCHS} scripts/gold/single.sh

EVAL_DATASET="MedMentions"
qsub -v EVAL_DATASET=${EVAL_DATASET} -v NUM_TRAIN_EPOCHS=${NUM_TRAIN_EPOCHS} scripts/gold/single.sh