# Dirs
DATA_DIR := data
TERM2CAT_DIR := $(DATA_DIR)/term2cat
TERM2CATS_DIR := $(DATA_DIR)/term2cats
DICT_DIR := $(DATA_DIR)/dict
UMLS_DIR := $(DATA_DIR)/2021AA
DBPEDIA_DIR := $(DATA_DIR)/DBPedia
PubChem_DIR := $(DATA_DIR)/PubChem
RAW_CORPUS_DIR := $(DATA_DIR)/raw
PUBMED := $(RAW_CORPUS_DIR)/pubmed
SOURCE_TXT_DIR := $(PUBMED)
PSEUDO_DATA_DIR := $(DATA_DIR)/pseudo
MODEL_DIR := $(DATA_DIR)/model
GOLD_DIR := $(DATA_DIR)/gold